"use client"

import { useEffect, useState } from "react"
import { Inter } from "next/font/google"
import Image from "next/image"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

const links = [
  {
    href: "/",
    label: "Dashbord",
  },
  {
    href: "/athletes/new",
    label: "Legg til ny utøver",
  },
  {
    href: "/templates/new",
    label: "Legg til ny mal",
  },
  {
    href: "/questions/new",
    label: "Legg til nytt spørsmål",
  },
]

export function Sidebar() {
  const [theme, setTheme] = useState("light")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setTheme(window.localStorage.getItem("theme") ?? "light")
    setMounted(true)
  }, [])

  useEffect(() => {
    if (!mounted) {
      return
    }

    document.body.className = `${inter.className} ${theme}`
    window.localStorage.setItem("theme", theme)
  }, [theme, mounted])

  const toggleTheme = () => {
    setTheme(theme === "light" ? "dark" : "light")
  }

  return (
    <div className="hidden border-r bg-gray-100/40 dark:bg-gray-800/40 lg:block">
      <div className="flex h-[80px] items-center border-b px-6">
        <Link className="flex items-center gap-2 font-semibold" href="/">
          <div className="h-12 w-12">
            <Image
              alt="Logo (generated by ChatGPT)"
              className="rounded-full"
              src="/img/logo.png"
              width={48}
              height={48}
            />
          </div>
          <span className="text-2xl">Evolve</span>
        </Link>
      </div>

      <div className="flex-1 overflow-auto py-2">
        <nav className="grid items-start px-4 text-sm font-medium">
          {links.map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-lg text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            >
              <span>{link.label}</span>
            </Link>
          ))}
        </nav>

        <div className="grid px-4">
          <button
            onClick={toggleTheme}
            className="mt-4 rounded-md bg-gray-600 px-4 py-2 text-sm font-medium text-white transition-colors duration-200 hover:bg-gray-700 dark:bg-gray-300 dark:text-gray-800 dark:hover:bg-gray-400"
          >
            Endre til {theme === "light" ? "mørkt" : "lyst"} tema
          </button>
        </div>
      </div>
    </div>
  )
}
